# Generated by Django 5.1.7 on 2025-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador del GIF', max_length=255)),
                ('imagen', models.ImageField(help_text='Archivo GIF', upload_to='gifs/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el GIF se usa actualmente en los estilos')),
            ],
        ),
    ]
